"""rename department

Revision ID: 461767ec8f70
Revises: 4aec56964dfe
Create Date: 2024-01-17 11:20:31.805184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461767ec8f70'
down_revision = '4aec56964dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
